# Generated by Django 4.2.1 on 2023-05-19 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isim', models.CharField(blank=True, max_length=50, null=True)),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
